<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit2cc417b4b715b6e5b3fff0ab890aae12
{
    public static $prefixLengthsPsr4 = array (
        'm' => 
        array (
            'marcfowler\\macaw\\' => 17,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'marcfowler\\macaw\\' => 
        array (
            0 => __DIR__ . '/..' . '/marcfowler/macaw',
        ),
    );

    public static $fallbackDirsPsr4 = array (
        0 => __DIR__ . '/../..' . '/../../',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit2cc417b4b715b6e5b3fff0ab890aae12::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit2cc417b4b715b6e5b3fff0ab890aae12::$prefixDirsPsr4;
            $loader->fallbackDirsPsr4 = ComposerStaticInit2cc417b4b715b6e5b3fff0ab890aae12::$fallbackDirsPsr4;

        }, null, ClassLoader::class);
    }
}
