<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit3cc09346040945401ff5f82d64fd190a
{
    public static $files = array (
        '036ec262f4bcc331fe80b225c0cd7b46' => __DIR__ . '/..' . '/terranc/blade/src/helpers.php',
    );

    public static $prefixLengthsPsr4 = array (
        't' => 
        array (
            'terranc\\Blade\\' => 14,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'terranc\\Blade\\' => 
        array (
            0 => __DIR__ . '/..' . '/terranc/blade/src',
        ),
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit3cc09346040945401ff5f82d64fd190a::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit3cc09346040945401ff5f82d64fd190a::$prefixDirsPsr4;

        }, null, ClassLoader::class);
    }
}
